version: "3.9"

services:
  test_db: #이거!!!!!
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: BookRecord
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: gojae
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    command:                              #한글 깨짐 방지
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci

#version: "3.3" # 파일 규격 버전
#services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
#  db: # 서비스 명
#    image: mysql:5.7 # 사용할 이미지
#    restart: always
#    #    container_name: mysql-test # 컨테이너 이름 설정
#    ports:
#      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
#    environment: # -e 옵션
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#      - MYSQL_DATABLE=example1
#      - TZ=UTC
#
#    command: # 명령어 실행
#      - --lower_case_table_names=1
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci