version: "3.9"

services:
  test_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: BookRecord
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: gojae
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    command:                              #한글 깨짐 방지
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
